/**
 * Database type definitions — generated by the Supabase CLI.
 *
 * This is a placeholder shape. Once you have migrations applied to a local
 * (or remote) Supabase project, regenerate this file so the whole monorepo
 * imports a fully-typed client:
 *
 *   pnpm --filter @app/supabase gen:types
 *   # or: supabase gen types typescript --local > packages/supabase/src/types.ts
 *
 * Commit the generated file so apps pick up the typed schema via @app/supabase.
 */
export type Database = {
  public: {
    CompositeTypes: Record<string, never>
    Enums: Record<string, never>
    Functions: Record<string, never>
    Tables: Record<string, never>
    Views: Record<string, never>
  }
}
