import '@/app/globals.css'

import type { Metadata, Viewport } from 'next'
import { Inter, Montserrat } from 'next/font/google'

import { Providers } from '@/app/providers'

const montserrat = Montserrat({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['400', '500', '600', '700', '800']
})

const inter = Inter({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500']
})

export const metadata: Metadata = {
  description:
    'A production-grade Next.js starter with fractal architecture, dark-glass design system, TanStack Query, and Zustand.',
  // metadataBase is required for fully-qualified Open Graph / Twitter URLs.
  // Point at the real production URL via an env var in deployed environments.
  metadataBase: new URL('http://localhost:3000'),
  title: {
    default: 'App — Dashboard',
    template: '%s · App'
  }
}

// Exported separately from `metadata` per Next 16 convention.
// themeColor aligns with the dark-glass design-system background token.
export const viewport: Viewport = {
  colorScheme: 'dark',
  themeColor: '#0b0b0f'
}

// ---------------------------------------------------------------------------
// Layout props — typed via the LayoutProps helper generated by `next typegen`.
// Convention: use LayoutProps<'/route'> for layouts; PageProps<'/route'> for
// pages. Generated types live in .next/types after running `next typegen`
// (which the `typecheck` script runs automatically before `tsc --noEmit`).
// ---------------------------------------------------------------------------
interface IRootLayoutProps {
  children: React.ReactNode
}

const RootLayout = ({ children }: IRootLayoutProps) => {
  return (
    <html
      className={`dark ${montserrat.variable} ${inter.variable}`}
      lang="en"
      suppressHydrationWarning
    >
      <body className="aurora min-h-screen bg-bg-base font-body text-text-primary antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
