import '@/app/globals.css'

import { DEFAULT_LANGUAGE, resources } from '@app/i18n'
import { DEFAULT_THEME } from '@app/tokens'
import type { Metadata, Viewport } from 'next'
import { Inter, Montserrat } from 'next/font/google'

import { SupabaseProviders } from '@/app/SupabaseProviders'
import { ThemeProvider } from '@/components/ThemeProvider'
import { NO_FLASH_THEME_SCRIPT } from '@/lib/theme/noFlashTheme.constant'

const montserrat = Montserrat({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['400', '500', '600', '700', '800']
})

const inter = Inter({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500']
})

export const metadata: Metadata = {
  description:
    'A production-grade Next.js starter with fractal architecture, glass design system, TanStack Query, and Zustand.',
  // metadataBase is required for fully-qualified Open Graph / Twitter URLs.
  // Point at the real production URL via an env var in deployed environments.
  metadataBase: new URL('http://localhost:3000'),
  title: {
    default: 'App — Dashboard',
    template: '%s · App'
  }
}

// Exported separately from `metadata` per Next 16 convention.
// 'dark light' lets the UA render form controls / scrollbars for whichever
// theme the user resolved to via cookie or prefers-color-scheme.
export const viewport: Viewport = {
  colorScheme: 'dark light'
}

// ---------------------------------------------------------------------------
// Layout props — typed via the LayoutProps helper generated by `next typegen`.
// Convention: use LayoutProps<'/route'> for layouts; PageProps<'/route'> for
// pages. Generated types live in .next/types after running `next typegen`
// (which the `typecheck` script runs automatically before `tsc --noEmit`).
// ---------------------------------------------------------------------------
interface IRootLayoutProps {
  children: React.ReactNode
}

const RootLayout = ({ children }: IRootLayoutProps) => {
  const messages = resources[DEFAULT_LANGUAGE].translation

  return (
    <html
      className={`${montserrat.variable} ${inter.variable}`}
      data-theme={DEFAULT_THEME}
      lang="en"
      suppressHydrationWarning
    >
      <head>
        {/* Blocking pre-paint script: resolves the theme before first paint
            (NEXT_THEME cookie first, else prefers-color-scheme) and overrides
            the static default data-theme above with zero flash. The layout
            stays static — reading cookies() here would make every route
            dynamic under Cache Components. */}
        <script
          dangerouslySetInnerHTML={{ __html: NO_FLASH_THEME_SCRIPT }}
        />
      </head>
      <body className="aurora min-h-screen bg-bg-base font-body text-text-primary antialiased">
        <ThemeProvider>
          <SupabaseProviders messages={messages}>
            {children}
          </SupabaseProviders>
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout
